{% set name = "jiwer" %}
{% set version = "3.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 2438acdc7ca22128fcab4be60db595809d2b5e73785b736de36dc3281a2a6ae8
  # check for the next version if the tag is correctly spelled (e.g. v3.0.5) and update it.
  - url: https://github.com/jitsi/{{ name }}/archive/refs/tags/v3.04.tar.gz
    sha256: d45fccc196468bc64308f517097ba8a49d833581178f5c9ceadbce8518256568
    folder: upstream_tests

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - jiwer = jiwer.cli:cli

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
  run:
    - python
    - rapidfuzz >=3.0.0,<4.0.0
    - click >=8.1.3,<9.0.0

test:
  source_files:
    - upstream_tests/tests
  imports:
    - jiwer
  commands:
    - pip check
    - jiwer --help
    - pytest -v upstream_tests/tests
  requires:
    - pip
    - pytest
    - pytest-benchmark

about:
  home: https://jitsi.github.io/jiwer
  summary: Evaluate your speech-to-text system with similarity measures such as word error rate (WER)
  description: |
    JiWER is a simple and fast python package to evaluate an automatic speech recognition system. It supports the following measures:
      * word error rate (WER)
      * match error rate (MER)
      * word information lost (WIL)
      * word information preserved (WIP)
      * character error rate (CER)
  license_family: Apache
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://jitsi.github.io/jiwer
  dev_url: https://github.com/jitsi/jiwer

extra:
  recipe-maintainers:
    - janjagusch
