{% set name = "jiwer" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jiwer-{{ version }}.tar.gz
  sha256: 4bfa525c4d5195cd413be4a2b148b7db043dec8c09a5692509504745fc7a0bc6

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - levenshtein ==0.20.2

test:
  imports:
    - jiwer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jitsi/jiwer
  summary: Evaluate your speech-to-text system with similarity measures such as word error rate (WER)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
